import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Provider } from "@/provider/provider";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/lib/tanstack";
import { Toaster } from "react-hot-toast";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { auth } from "@/auth";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isAuthenticated = !!session;

  return (
    <html
      lang="en"
      className={`${poppins.variable} ${montserrat.variable}  antialiased`}
    >
      <body>
        <QueryClientProvider client={queryClient}>
          <Provider>
            {isAuthenticated && <Navbar />}
            <Toaster />
            <ReactQueryDevtools initialIsOpen={true} />
            {children}
            {isAuthenticated && <Footer />}
          </Provider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
